apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minio
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/KwIlnn/DataEngineeringMLOps.git
    path: infrastructure
    targetRevision: main
    directory:
      recurse: true

  destination:
    server: https://kubernetes.default.svc

  syncPolicy:
    automated:
      prune: true
      selfHeal: true