apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minio
  namespace: argocd
spec:
  project: default

  sources:
  -  repoURL: oci://registry-1.docker.io/bitnamicharts/minio
     targetRevision: 17.0.21
     helm:
       valueFiles:
        - $values/minio-values.yaml

  -  repoURL: https://github.com/KwIlnn/DataEngineeringMLOps.git
     targetRevision: main
     path: helm-values
     ref: values

  destination:
    server: https://kubernetes.default.svc
    namespace: argocd

  syncPolicy:
    automated:
      prune: true
      selfHeal: true