apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minio
  namespace: argocd
spec:
  project: default

  source:
    repoURL: oci://registry-1.docker.io/bitnamicharts/minio
    chart: minio
    targetRevision: 14.7.1
    helm:
      valueFiles:
        - $values/minio-values.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: minio

  syncPolicy:
    automated:
      prune: true
      selfHeal: true